//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bank_Balance
    {
        public int Id { get; set; }
        public int AssetId { get; set; }
        public System.DateTime BalanceDate { get; set; }
        public decimal Balance { get; set; }
    }
}
