//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TestBankEntities : DbContext
    {
        public TestBankEntities()
            : base("name=TestBankEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bank_Account> Bank_Account { get; set; }
        public virtual DbSet<Bank_Balance> Bank_Balance { get; set; }
        public virtual DbSet<Bank_Transaction> Bank_Transaction { get; set; }
        public virtual DbSet<Raw_Bank_Balance> Raw_Bank_Balance { get; set; }
        public virtual DbSet<Raw_Bank_Transaction> Raw_Bank_Transaction { get; set; }
    
        public virtual ObjectResult<SpGetLog_Result> SpGetLog()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SpGetLog_Result>("SpGetLog");
        }
    }
}
