//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Raw_Bank_Transaction
    {
        public int Id { get; set; }
        public string FinalStatus { get; set; }
        public Nullable<int> RelatedId { get; set; }
        public string AccNo { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> RunningBalance { get; set; }
    }
}
